# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Storage'

target 'MelanomaClassifier' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for MelanomaClassifier

  target 'MelanomaClassifierTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MelanomaClassifierUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
